name: Model Tests

on:
  schedule:
    - cron: "0 0 * * 0"  # Weekly test on Sunday

jobs:
  model_validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate AI Models
        run: python validate_models.py
